FROM app-image AS test-image

WORKDIR /app

COPY Pipfile* .
RUN PIPENV_VENV_IN_PROJECT=1 pipenv install --dev --deploy --ignore-pipfile
#COPY . /app/


#ENTRYPOINT ["./.venv/bin/python3", "./.venv/bin/pytest"]