version: '3.3'
services:

  pipeline:
    build:
      context: .
      dockerfile: Dockerfile
      target: scheduler-image
      args:
        NB_USER: "${NB_USER}"
        NB_UID: "${NB_UID}"
        NB_GID: "${NB_GID}"
        APP_DIR_NAME: "${APP_DIR_NAME}"
        HOME_DIR_NAME: "${HOME_DIR_NAME}"
        CRONTAB_FILE: "${CRONTAB_FILE}"
        PAPERTRAIL_URL: "${PAPERTRAIL_URL}"
    restart: always
    logging:
      driver: syslog
      options:
        syslog-address: "udp://${PAPERTRAIL_URL}"
        tag: "{{.Name}}/{{.ID}}"
    env_file:
      - ./nanoHUB/.env
#    command: bash -c "sudo --preserve-env cron -f && tail -f /var/log/cron.log"
    command: bash -c "sudo --preserve-env /usr/bin/supervisord"