version: '3.4'
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev-image
      labels:
        com.nanoHUB.description: "Development and Exploration service"
      args:
        UBUNTU_VERSION: "${UBUNTU_VERSION}"
        NB_USER: "${NB_USER}"
        NB_UID: "${NB_UID}"
        NB_GID: "${NB_GID}"
        APP_DIR_NAME: "${APP_DIR_NAME}"
        HOME_DIR_NAME: "${HOME_DIR_NAME}"
        JUPYTER_DISPLAY_IP_ADDRESS: "${JUPYTER_DISPLAY_IP_ADDRESS}"
        ORIGIN_IP_ADDRESS: "${ORIGIN_IP_ADDRESS}"
        JUPYTER_IP_ADDRESS: "${JUPYTER_IP_ADDRESS}"
        JUPYTER_PORT: "${JUPYTER_PORT}"
        BUILD_WITH_JUPYTER: "${BUILD_WITH_JUPYTER}"
        LANG: "${LANG}"
        LC_ALL: "${LC_ALL}"
        LOCALE: "${LOCALE}"
        CPUS: "${CPUS}"
        PHP_VERSION: "${PHP_VERSION}"
        COMPOSER_SIGNATURE: "${COMPOSER_SIGNATURE}"
    restart: always
    ports:
      - "${JUPYTER_PORT}:${JUPYTER_PORT}"
    volumes:
      - ".:/${HOME_DIR_NAME}/${NB_USER}/${APP_DIR_NAME}"
    env_file:
      - ./nanoHUB/.env
      - ./nanoHUB/.config
    command: [jupyter, lab]
#    command: bash -c "tail -f /dev/stdout"