version: '3.3'
services:

  jupyter:
    image: jupyter/base-notebook:latest
    ports:
      - "8888:8888"
    links:
      - postgres
    volumes:
      - ".:/home/jovyan/work"
    restart: always
    environment:
      JUPYTER_ENABLE_LAB: 1
      NB_USER: jovyan
      NB_GID: 1000
      CHOWN_HOME: 'yes'
      CHOWN_HOME_OPTS: '-R'
    command: bash -c "
        pip install --upgrade setuptools pip wheel &&
        pip install --no-cache-dir pipenv &&
        cd work && pipenv lock -r > requirements.txt && pip install -r requirements.txt &&
        export PYTHONPATH="$PYTHONPATH:/home/jovyan/work" &&
        jupyter notebook
      "


  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: data
      POSTGRES_PASSWORD: data
      POSTGRES_DB: data