version: '3.3'
services:

  dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev-image
      args:
        NB_USER: "${NB_USER}"
        APP_DIR_NAME: "${APP_DIR_NAME}"
        HOME_DIR_NAME: "${HOME_DIR_NAME}"
        JUPYTER_PORT: "${JUPYTER_PORT}"
    restart: always
    ports:
      - "${JUPYTER_PORT}:${JUPYTER_PORT}"
    volumes:
      - ".:/${HOME_DIR_NAME}/${NB_USER}/${APP_DIR_NAME}"
    env_file:
      - ./nanoHUB/.env
