version: '3.3'
services:
  app:
    container_name: app
    restart: always
    build: nanoHUB/clustering

  test:
    container_name: test
    build:
      context: nanoHUB/clustering
      dockerfile: Dockerfile.test
    depends_on: [app]

  mysql:
    image: mariadb:10.5
    container_name: dev_db
    volumes:
      - ./data:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nanohub
    ports:
      - 3306:3306
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    restart: always

