version: '3.3'
services:

  jupyter:
    image: jupyter/base-notebook:latest
    ports:
      - "8888:8888"
    links:
      - postgres
    volumes:
      - ".:/home/jovyan/work"
    restart: always
    environment:
      JUPYTER_ENABLE_LAB: 1
      NB_USER: jovyan
      NB_GID: 1000
      CHOWN_HOME: 'yes'
      CHOWN_HOME_OPTS: '-R'

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: data
      POSTGRES_PASSWORD: data
      POSTGRES_DB: data