version: "3.3"
services:
  tasks:
    container_name: tasks_container
    build:
      context: .
      dockerfile: docker/tasks/Dockerfile
      args:
        - CRONTAB_FILEPATH=$crontab_path
        - ENVVARS_FILEPATH=$envvars_file_path
    restart: always
    volumes:
      - ".:/app/"
    logging:
      driver: gelf
      options:
        gelf-address: udp://127.0.0.1:12201
        tag: "staging"
    links:
      - logstash:logstash
    depends_on:
      - logstash
    command: tail -f /dev/null
    environment:
      - TZ=America/New_York

  cronjob_runner:
    container_name: cronjob_runner_container
    build:
      context: .
      dockerfile: ./docker/cronjobs/Dockerfile
      args:
        - CRONTAB_FILEPATH=$crontab_path
        - ENVVARS_FILEPATH=$envvars_file_path
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    logging:
      driver: gelf
      options:
        gelf-address: udp://127.0.0.1:12201
        tag: "staging"
    links:
      - logstash:logstash
    depends_on:
      - logstash
    environment:
      - TZ=America/New_York

  logstash:
    image: logstash:7.12.0
    container_name: logstash-container
    restart: unless-stopped
    ports:
      - "12201:12201/udp"
    volumes:
      - ./config/logstash.conf:/etc/logstash.conf
    command: bash -c "
        rm -f /usr/share/logstash/pipeline/logstash.conf &&
        rm -f /usr/share/logstash/config/logstash.yml &&
        touch /usr/share/logstash/config/logstash.yml &&
        rm -f /usr/share/logstash/config/logstash-sample.conf &&
        bin/logstash-plugin install logstash-output-newrelic &&
        bin/logstash-plugin install logstash-output-loggly &&
        bin/logstash-plugin install logstash-input-gelf &&
        sudo chown --recursive logstash /etc/logstash.conf &&
        logstash -f /etc/logstash.conf
      "
    environment:
      - NEWRELIC_LICENSE_KEY=$newrelic_license_key
      - LOGGLY_LICENSE_KEY=$loggly_license_key