"""add uniqueness to cluster span

Revision ID: 0cde9897b507
Revises: 6cef3b8bd69e
Create Date: 2022-06-16 22:29:24.298326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cde9897b507'
down_revision = '6cef3b8bd69e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
