"""add uniqueness to cluster span

Revision ID: 6cef3b8bd69e
Revises: 760411f63420
Create Date: 2022-06-16 22:27:58.260987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cef3b8bd69e'
down_revision = '760411f63420'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
