"""Add unique to algorithm name

Revision ID: 760411f63420
Revises: e79931189298
Create Date: 2022-06-16 22:23:12.622769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '760411f63420'
down_revision = 'e79931189298'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
