"""add uniqueness to cluster span

Revision ID: a178a3e44feb
Revises: 0cde9897b507
Create Date: 2022-06-16 22:33:53.255275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a178a3e44feb'
down_revision = '0cde9897b507'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_from_to_datetime_uc', 'cluster_span', ['from_datetime', 'to_datetime'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_from_to_datetime_uc', 'cluster_span', type_='unique')
    # ### end Alembic commands ###
