"""Added initial table

Revision ID: da39de5920a6
Revises: 
Create Date: 2022-06-16 22:13:34.281596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da39de5920a6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('algorithm_info',
    sa.Column('create_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_updated_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('meta_json', sa.Text(), nullable=True),
    sa.Column('comment', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('cluster_span',
    sa.Column('create_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_updated_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('meta_json', sa.Text(), nullable=True),
    sa.Column('comment', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('by_day', 'by_month', 'by_semester', 'by_year', 'by_week'), nullable=True),
    sa.Column('from_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('to_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('record_update_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_processed_id', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_processed__updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_record_update_history_last_processed_id'), 'record_update_history', ['last_processed_id'], unique=True)
    op.create_table('cluster_info',
    sa.Column('create_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_updated_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('meta_json', sa.Text(), nullable=True),
    sa.Column('comment', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('algorithm_id', sa.Integer(), nullable=True),
    sa.Column('span_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['algorithm_id'], ['algorithm_info.id'], ),
    sa.ForeignKeyConstraint(['span_id'], ['cluster_span.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('clusters_users',
    sa.Column('create_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_updated_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('meta_json', sa.Text(), nullable=True),
    sa.Column('comment', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['cluster_info.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'cluster_id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clusters_users')
    op.drop_table('cluster_info')
    op.drop_index(op.f('ix_record_update_history_last_processed_id'), table_name='record_update_history')
    op.drop_table('record_update_history')
    op.drop_table('cluster_span')
    op.drop_table('algorithm_info')
    # ### end Alembic commands ###
