version: '3.3'
services:
  clustering:
    container_name: clustering
    build: .
    volumes:
      - ".:/app/"
    restart: always
    user: user
    labels:
      ofelia.enabled: "true"
    #      ofelia.job-exec.app.slack-webhook: "slack-webhook-url"
    environment:
      - TZ=America/New_York
    command: tail -f /dev/null

  scheduler:
    image: mcuadros/ofelia:latest
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./scheduler/config.ini:/etc/ofelia/config.ini
    depends_on:
      - clustering
#  elasticsearch:
#    image: elasticsearch:7.12.1
#    restart: on-failure
#    ports:
#      - 9200:9200
#      - 9300:9300
#    volumes:
#      - "./config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml"
#    depends_on:
#      - clustering
#  kibana:
#    image: kibana:7.12.1
#    ports:
#      - 5601:5601
#    depends_on:
#      - elasticsearch
#    external_links:
#      - elasticsearch:elasticsearch
#  logstash:
#    image: logstash:7.12.1
#    command: logstash -f /etc/logstash/conf.d/logstash.conf
#    external_links:
#      - elasticsearch:elasticsearch
#    restart: on-failure
#    volumes:
#      - ./config/logstash.conf:/etc/logstash/conf.d/logstash.conf
#      - ./.log:/tmp/logs