"""add toolevent

Revision ID: 026465bf4e2f
Revises: 59212f2186cb
Create Date: 2021-08-08 23:13:43.559455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '026465bf4e2f'
down_revision = '59212f2186cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('descriptors_tool_events',
    sa.Column('toolevents__first_start_date', sa.DateTime(), nullable=True),
    sa.Column('toolevents__last_start_date', sa.DateTime(), nullable=True),
    sa.Column('toolevents__first_finish_date', sa.DateTime(), nullable=True),
    sa.Column('toolevents__last_finish_date', sa.DateTime(), nullable=True),
    sa.Column('toolevents__lifetime', sa.Integer(), nullable=True, comment='days from first to last simulation'),
    sa.Column('toolevents__count', sa.Integer(), nullable=True, comment='number of simulations'),
    sa.Column('toolevents__activity_days', sa.Integer(), nullable=True, comment='count of days spent performing simulations'),
    sa.Column('toolevents__tools_used_names', sa.Text(), nullable=True, comment='names of tools used in simulations'),
    sa.Column('toolevents__tools_used_count', sa.Integer(), nullable=True, comment='number of tools used in simulations'),
    sa.Column('toolevents__active_days', sa.Integer(), nullable=True, comment='count of days performing any activity'),
    sa.Column('average_freqency', sa.Numeric(), nullable=True, comment='F = lifetime in days / Days spent on nanoHUB'),
    sa.Column('_last_updated', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('registration_date', sa.DateTime(), nullable=True),
    sa.Column('last_visit_date', sa.DateTime(), nullable=True),
    sa.Column('lifetime_days', sa.Integer(), nullable=True, comment='last day - registration day'),
    sa.Column('_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_descriptors_tool_events__last_updated'), 'descriptors_tool_events', ['_last_updated'], unique=False)
    op.create_index(op.f('ix_descriptors_tool_events_average_freqency'), 'descriptors_tool_events', ['average_freqency'], unique=False)
    op.create_index(op.f('ix_descriptors_tool_events_last_visit_date'), 'descriptors_tool_events', ['last_visit_date'], unique=False)
    op.create_index(op.f('ix_descriptors_tool_events_registration_date'), 'descriptors_tool_events', ['registration_date'], unique=False)
    op.create_index(op.f('ix_descriptors_tool_events_toolevents__first_finish_date'), 'descriptors_tool_events', ['toolevents__first_finish_date'], unique=False)
    op.create_index(op.f('ix_descriptors_tool_events_toolevents__first_start_date'), 'descriptors_tool_events', ['toolevents__first_start_date'], unique=False)
    op.create_index(op.f('ix_descriptors_tool_events_toolevents__last_finish_date'), 'descriptors_tool_events', ['toolevents__last_finish_date'], unique=False)
    op.create_index(op.f('ix_descriptors_tool_events_toolevents__last_start_date'), 'descriptors_tool_events', ['toolevents__last_start_date'], unique=False)
    op.create_table('temp_descriptors_tool_events',
    sa.Column('first_sim_date', sa.DateTime(), nullable=True),
    sa.Column('last_sim_date', sa.DateTime(), nullable=True),
    sa.Column('sims_lifetime', sa.Integer(), nullable=True, comment='days from first to last simulation'),
    sa.Column('sims_count', sa.Integer(), nullable=True, comment='number of simulations'),
    sa.Column('sims_activity_days', sa.Integer(), nullable=True, comment='count of days spent performing simulations'),
    sa.Column('tools_used_names', sa.Text(), nullable=True, comment='names of tools used in simulations'),
    sa.Column('tools_used_count', sa.Integer(), nullable=True, comment='number of tools used in simulations'),
    sa.Column('active_days', sa.Integer(), nullable=True, comment='count of days performing any activity'),
    sa.Column('average_freqency', sa.Numeric(), nullable=True, comment='F = lifetime in days / Days spent on nanoHUB'),
    sa.Column('_last_updated', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('temp_id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('temp_id'),
    sa.UniqueConstraint('user'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_temp_descriptors_tool_events__last_updated'), 'temp_descriptors_tool_events', ['_last_updated'], unique=False)
    op.create_index(op.f('ix_temp_descriptors_tool_events_average_freqency'), 'temp_descriptors_tool_events', ['average_freqency'], unique=False)
    op.create_index(op.f('ix_temp_descriptors_tool_events_first_sim_date'), 'temp_descriptors_tool_events', ['first_sim_date'], unique=False)
    op.create_index(op.f('ix_temp_descriptors_tool_events_last_sim_date'), 'temp_descriptors_tool_events', ['last_sim_date'], unique=False)
    op.create_table('toolevent_update_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_processed_toolevent_id', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('last_processed_toolevent_id_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_toolevent_update_history_last_processed_toolevent_id'), 'toolevent_update_history', ['last_processed_toolevent_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_toolevent_update_history_last_processed_toolevent_id'), table_name='toolevent_update_history')
    op.drop_table('toolevent_update_history')
    op.drop_index(op.f('ix_temp_descriptors_tool_events_last_sim_date'), table_name='temp_descriptors_tool_events')
    op.drop_index(op.f('ix_temp_descriptors_tool_events_first_sim_date'), table_name='temp_descriptors_tool_events')
    op.drop_index(op.f('ix_temp_descriptors_tool_events_average_freqency'), table_name='temp_descriptors_tool_events')
    op.drop_index(op.f('ix_temp_descriptors_tool_events__last_updated'), table_name='temp_descriptors_tool_events')
    op.drop_table('temp_descriptors_tool_events')
    op.drop_index(op.f('ix_descriptors_tool_events_toolevents__last_start_date'), table_name='descriptors_tool_events')
    op.drop_index(op.f('ix_descriptors_tool_events_toolevents__last_finish_date'), table_name='descriptors_tool_events')
    op.drop_index(op.f('ix_descriptors_tool_events_toolevents__first_start_date'), table_name='descriptors_tool_events')
    op.drop_index(op.f('ix_descriptors_tool_events_toolevents__first_finish_date'), table_name='descriptors_tool_events')
    op.drop_index(op.f('ix_descriptors_tool_events_registration_date'), table_name='descriptors_tool_events')
    op.drop_index(op.f('ix_descriptors_tool_events_last_visit_date'), table_name='descriptors_tool_events')
    op.drop_index(op.f('ix_descriptors_tool_events_average_freqency'), table_name='descriptors_tool_events')
    op.drop_index(op.f('ix_descriptors_tool_events__last_updated'), table_name='descriptors_tool_events')
    op.drop_table('descriptors_tool_events')
    # ### end Alembic commands ###
