"""Add auto-update timestamp

Revision ID: 165b225d3c4c
Revises: 298f37df5867
Create Date: 2021-08-03 13:20:39.814096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '165b225d3c4c'
down_revision = '298f37df5867'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_descriptors', sa.Column('last_updated', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False))
    op.create_index(op.f('ix_user_descriptors_last_updated'), 'user_descriptors', ['last_updated'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_descriptors_last_updated'), table_name='user_descriptors')
    op.drop_column('user_descriptors', 'last_updated')
    # ### end Alembic commands ###
