"""rename earliest-latest sim dates

Revision ID: 1a750e6eebea
Revises: a5fe51834e98
Create Date: 2021-08-05 13:43:13.421518

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1a750e6eebea'
down_revision = 'a5fe51834e98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_descriptors', sa.Column('earliest_simulation_date', sa.DateTime(), nullable=True))
    op.add_column('user_descriptors', sa.Column('latest_simulation_date', sa.DateTime(), nullable=True))
    op.drop_index('ix_user_descriptors_earliest_simulation', table_name='user_descriptors')
    op.drop_index('ix_user_descriptors_latest_simulation', table_name='user_descriptors')
    op.create_index(op.f('ix_user_descriptors_earliest_simulation_date'), 'user_descriptors', ['earliest_simulation_date'], unique=False)
    op.create_index(op.f('ix_user_descriptors_latest_simulation_date'), 'user_descriptors', ['latest_simulation_date'], unique=False)
    op.drop_column('user_descriptors', 'latest_simulation')
    op.drop_column('user_descriptors', 'earliest_simulation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_descriptors', sa.Column('earliest_simulation', mysql.DATETIME(), nullable=True))
    op.add_column('user_descriptors', sa.Column('latest_simulation', mysql.DATETIME(), nullable=True))
    op.drop_index(op.f('ix_user_descriptors_latest_simulation_date'), table_name='user_descriptors')
    op.drop_index(op.f('ix_user_descriptors_earliest_simulation_date'), table_name='user_descriptors')
    op.create_index('ix_user_descriptors_latest_simulation', 'user_descriptors', ['latest_simulation'], unique=False)
    op.create_index('ix_user_descriptors_earliest_simulation', 'user_descriptors', ['earliest_simulation'], unique=False)
    op.drop_column('user_descriptors', 'latest_simulation_date')
    op.drop_column('user_descriptors', 'earliest_simulation_date')
    # ### end Alembic commands ###
