"""fix user name in temp table

Revision ID: 3073a8491b04
Revises: 5e9b00023fbe
Create Date: 2021-08-05 14:37:27.109178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3073a8491b04'
down_revision = '5e9b00023fbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('temp_user_descriptor', sa.Column('user', sa.String(length=150), nullable=True))
    op.create_unique_constraint(None, 'temp_user_descriptor', ['user'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'temp_user_descriptor', type_='unique')
    op.drop_column('temp_user_descriptor', 'user')
    # ### end Alembic commands ###
