"""move lifetime_days

Revision ID: 385cc1a415a8
Revises: 54bcf4bfcd73
Create Date: 2021-08-05 14:45:20.247579

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '385cc1a415a8'
down_revision = '54bcf4bfcd73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('temp_user_descriptor', 'active_days',
               existing_type=mysql.INTEGER(display_width=11),
               comment='count of days performing any activity',
               existing_comment='cound of days performing any activity',
               existing_nullable=True)
    op.drop_column('temp_user_descriptor', 'lifetime_days')
    op.alter_column('user_descriptor', 'active_days',
               existing_type=mysql.INTEGER(display_width=11),
               comment='count of days performing any activity',
               existing_comment='cound of days performing any activity',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_descriptor', 'active_days',
               existing_type=mysql.INTEGER(display_width=11),
               comment='cound of days performing any activity',
               existing_comment='count of days performing any activity',
               existing_nullable=True)
    op.add_column('temp_user_descriptor', sa.Column('lifetime_days', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='last day - registration day'))
    op.alter_column('temp_user_descriptor', 'active_days',
               existing_type=mysql.INTEGER(display_width=11),
               comment='cound of days performing any activity',
               existing_comment='count of days performing any activity',
               existing_nullable=True)
    # ### end Alembic commands ###
