"""add earliest latest sims

Revision ID: 39120e4b932c
Revises: 026ac09cdfde
Create Date: 2021-08-04 14:43:51.103697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39120e4b932c'
down_revision = '026ac09cdfde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
