"""Generate for user_descriptors

Revision ID: 4465582f52c9
Revises: 
Create Date: 2021-08-02 16:17:20.144938

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4465582f52c9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_descriptors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('simulation_lifetime', sa.Integer(), nullable=True),
    sa.Column('num_simulations_run', sa.Integer(), nullable=True),
    sa.Column('name_tools_used', sa.Text(), nullable=True),
    sa.Column('num_tools_used', sa.Integer(), nullable=True),
    sa.Column('num_days_spent', sa.Integer(), nullable=True, comment='total number of days spent on nanoHUB'),
    sa.Column('user_lifetime', sa.Integer(), nullable=True, comment='last day - registration day'),
    sa.Column('average_freqency', sa.Numeric(), nullable=True, comment='F = lifetime in days / Days spent on nanoHUB'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_user_descriptors_average_freqency'), 'user_descriptors', ['average_freqency'], unique=False)
    op.drop_index('ix_user_descriptors_average_freqency', table_name='user_descriptors_1')
    op.drop_index('username', table_name='user_descriptors_1')
    op.drop_table('user_descriptors_1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_descriptors_1',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('simulation_lifetime', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('num_simulations_run', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('name_tools_used', mysql.TEXT(), nullable=True),
    sa.Column('num_tools_used', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('num_days_spent', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='total number of days spent on nanoHUB'),
    sa.Column('user_lifetime', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='last day - registration day'),
    sa.Column('average_freqency', mysql.DECIMAL(precision=10, scale=0), nullable=True, comment='F = lifetime in days / Days spent on nanoHUB'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('username', 'user_descriptors_1', ['username'], unique=False)
    op.create_index('ix_user_descriptors_average_freqency', 'user_descriptors_1', ['average_freqency'], unique=False)
    op.drop_index(op.f('ix_user_descriptors_average_freqency'), table_name='user_descriptors')
    op.drop_table('user_descriptors')
    # ### end Alembic commands ###
