"""Add registerDate

Revision ID: 4faed01e181e
Revises: bf8694751e53
Create Date: 2021-08-02 21:15:17.427031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4faed01e181e'
down_revision = 'bf8694751e53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_descriptors', sa.Column('registerDate', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_user_descriptors_registerDate'), 'user_descriptors', ['registerDate'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_descriptors_registerDate'), table_name='user_descriptors')
    op.drop_column('user_descriptors', 'registerDate')
    # ### end Alembic commands ###
