"""fix tools used name and count

Revision ID: 54bcf4bfcd73
Revises: 3073a8491b04
Create Date: 2021-08-05 14:41:39.732059

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '54bcf4bfcd73'
down_revision = '3073a8491b04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('temp_user_descriptor', sa.Column('tools_used_names', sa.Text(), nullable=True, comment='names of tools used in simulations'))
    op.add_column('temp_user_descriptor', sa.Column('tools_used_count', sa.Integer(), nullable=True, comment='number of tools used in simulations'))
    op.drop_column('temp_user_descriptor', 'tools_used')
    op.drop_column('temp_user_descriptor', 'tools_count')
    op.add_column('user_descriptor', sa.Column('tools_used_names', sa.Text(), nullable=True, comment='names of tools used in simulations'))
    op.add_column('user_descriptor', sa.Column('tools_used_count', sa.Integer(), nullable=True, comment='number of tools used in simulations'))
    op.drop_column('user_descriptor', 'tools_used')
    op.drop_column('user_descriptor', 'tools_count')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_descriptor', sa.Column('tools_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='number of tools used in simulations'))
    op.add_column('user_descriptor', sa.Column('tools_used', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True, comment='names of tools used in simulations'))
    op.drop_column('user_descriptor', 'tools_used_count')
    op.drop_column('user_descriptor', 'tools_used_names')
    op.add_column('temp_user_descriptor', sa.Column('tools_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='number of tools used in simulations'))
    op.add_column('temp_user_descriptor', sa.Column('tools_used', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True, comment='names of tools used in simulations'))
    op.drop_column('temp_user_descriptor', 'tools_used_count')
    op.drop_column('temp_user_descriptor', 'tools_used_names')
    # ### end Alembic commands ###
