"""fix attributes

Revision ID: 5e9b00023fbe
Revises: d8d71a5fcbdf
Create Date: 2021-08-05 14:36:05.523746

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5e9b00023fbe'
down_revision = 'd8d71a5fcbdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('temp_user_descriptor', sa.Column('first_sim_date', sa.DateTime(), nullable=True))
    op.add_column('temp_user_descriptor', sa.Column('last_sim_date', sa.DateTime(), nullable=True))
    op.add_column('temp_user_descriptor', sa.Column('sims_lifetime', sa.Integer(), nullable=True, comment='days from first to last simulation'))
    op.add_column('temp_user_descriptor', sa.Column('sims_count', sa.Integer(), nullable=True, comment='number of simulations'))
    op.add_column('temp_user_descriptor', sa.Column('sims_activity_days', sa.Integer(), nullable=True, comment='count of days spent performing simulations'))
    op.add_column('temp_user_descriptor', sa.Column('tools_used', sa.Text(), nullable=True, comment='names of tools used in simulations'))
    op.add_column('temp_user_descriptor', sa.Column('tools_count', sa.Integer(), nullable=True, comment='number of tools used in simulations'))
    op.add_column('temp_user_descriptor', sa.Column('active_days', sa.Integer(), nullable=True, comment='cound of days performing any activity'))
    op.add_column('temp_user_descriptor', sa.Column('lifetime_days', sa.Integer(), nullable=True, comment='last day - registration day'))
    op.add_column('temp_user_descriptor', sa.Column('average_freqency', sa.Numeric(), nullable=True, comment='F = lifetime in days / Days spent on nanoHUB'))
    op.drop_index('ix_temp_user_descriptor_last_visit_date', table_name='temp_user_descriptor')
    op.drop_index('ix_temp_user_descriptor_registration_date', table_name='temp_user_descriptor')
    op.drop_index('username', table_name='temp_user_descriptor')
    op.create_index(op.f('ix_temp_user_descriptor_average_freqency'), 'temp_user_descriptor', ['average_freqency'], unique=False)
    op.create_index(op.f('ix_temp_user_descriptor_first_sim_date'), 'temp_user_descriptor', ['first_sim_date'], unique=False)
    op.create_index(op.f('ix_temp_user_descriptor_last_sim_date'), 'temp_user_descriptor', ['last_sim_date'], unique=False)
    op.drop_column('temp_user_descriptor', 'email')
    op.drop_column('temp_user_descriptor', 'username')
    op.drop_column('temp_user_descriptor', 'name')
    op.drop_column('temp_user_descriptor', 'registration_date')
    op.drop_column('temp_user_descriptor', 'last_visit_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('temp_user_descriptor', sa.Column('last_visit_date', mysql.DATETIME(), nullable=True))
    op.add_column('temp_user_descriptor', sa.Column('registration_date', mysql.DATETIME(), nullable=True))
    op.add_column('temp_user_descriptor', sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
    op.add_column('temp_user_descriptor', sa.Column('username', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=150), nullable=True))
    op.add_column('temp_user_descriptor', sa.Column('email', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=150), nullable=True))
    op.drop_index(op.f('ix_temp_user_descriptor_last_sim_date'), table_name='temp_user_descriptor')
    op.drop_index(op.f('ix_temp_user_descriptor_first_sim_date'), table_name='temp_user_descriptor')
    op.drop_index(op.f('ix_temp_user_descriptor_average_freqency'), table_name='temp_user_descriptor')
    op.create_index('username', 'temp_user_descriptor', ['username'], unique=False)
    op.create_index('ix_temp_user_descriptor_registration_date', 'temp_user_descriptor', ['registration_date'], unique=False)
    op.create_index('ix_temp_user_descriptor_last_visit_date', 'temp_user_descriptor', ['last_visit_date'], unique=False)
    op.drop_column('temp_user_descriptor', 'average_freqency')
    op.drop_column('temp_user_descriptor', 'lifetime_days')
    op.drop_column('temp_user_descriptor', 'active_days')
    op.drop_column('temp_user_descriptor', 'tools_count')
    op.drop_column('temp_user_descriptor', 'tools_used')
    op.drop_column('temp_user_descriptor', 'sims_activity_days')
    op.drop_column('temp_user_descriptor', 'sims_count')
    op.drop_column('temp_user_descriptor', 'sims_lifetime')
    op.drop_column('temp_user_descriptor', 'last_sim_date')
    op.drop_column('temp_user_descriptor', 'first_sim_date')
    # ### end Alembic commands ###
