"""add sims_activity_days

Revision ID: 6757b3cea427
Revises: 3295ba0b3b8b
Create Date: 2021-08-05 15:25:32.029577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6757b3cea427'
down_revision = '3295ba0b3b8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('record_update_history', sa.Column('last_processed_toolstart_id', sa.BigInteger(), server_default='0', nullable=False))
    op.add_column('record_update_history', sa.Column('last_processed_toolstart_id_updated', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_record_update_history_last_processed_toolstart_id'), 'record_update_history', ['last_processed_toolstart_id'], unique=True)
    op.add_column('temp_user_descriptor', sa.Column('_last_updated', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False))
    op.add_column('temp_user_descriptor', sa.Column('_created', sa.DateTime(), nullable=True))
    op.add_column('temp_user_descriptor', sa.Column('first_sim_date', sa.DateTime(), nullable=True))
    op.add_column('temp_user_descriptor', sa.Column('last_sim_date', sa.DateTime(), nullable=True))
    op.add_column('temp_user_descriptor', sa.Column('sims_lifetime', sa.Integer(), nullable=True, comment='days from first to last simulation'))
    op.add_column('temp_user_descriptor', sa.Column('sims_count', sa.Integer(), nullable=True, comment='number of simulations'))
    op.add_column('temp_user_descriptor', sa.Column('sims_activity_days', sa.Integer(), nullable=True, comment='count of days spent performing simulations'))
    op.add_column('temp_user_descriptor', sa.Column('tools_used_names', sa.Text(), nullable=True, comment='names of tools used in simulations'))
    op.add_column('temp_user_descriptor', sa.Column('tools_used_count', sa.Integer(), nullable=True, comment='number of tools used in simulations'))
    op.add_column('temp_user_descriptor', sa.Column('active_days', sa.Integer(), nullable=True, comment='count of days performing any activity'))
    op.add_column('temp_user_descriptor', sa.Column('average_freqency', sa.Numeric(), nullable=True, comment='F = lifetime in days / Days spent on nanoHUB'))
    op.add_column('temp_user_descriptor', sa.Column('user', sa.String(length=150), nullable=True))
    op.create_index(op.f('ix_temp_user_descriptor__last_updated'), 'temp_user_descriptor', ['_last_updated'], unique=False)
    op.create_index(op.f('ix_temp_user_descriptor_average_freqency'), 'temp_user_descriptor', ['average_freqency'], unique=False)
    op.create_index(op.f('ix_temp_user_descriptor_first_sim_date'), 'temp_user_descriptor', ['first_sim_date'], unique=False)
    op.create_index(op.f('ix_temp_user_descriptor_last_sim_date'), 'temp_user_descriptor', ['last_sim_date'], unique=False)
    op.create_unique_constraint(None, 'temp_user_descriptor', ['user'])
    op.add_column('user_descriptor', sa.Column('_last_updated', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False))
    op.add_column('user_descriptor', sa.Column('_created', sa.DateTime(), nullable=True))
    op.add_column('user_descriptor', sa.Column('first_sim_date', sa.DateTime(), nullable=True))
    op.add_column('user_descriptor', sa.Column('last_sim_date', sa.DateTime(), nullable=True))
    op.add_column('user_descriptor', sa.Column('sims_lifetime', sa.Integer(), nullable=True, comment='days from first to last simulation'))
    op.add_column('user_descriptor', sa.Column('sims_count', sa.Integer(), nullable=True, comment='number of simulations'))
    op.add_column('user_descriptor', sa.Column('sims_activity_days', sa.Integer(), nullable=True, comment='count of days spent performing simulations'))
    op.add_column('user_descriptor', sa.Column('tools_used_names', sa.Text(), nullable=True, comment='names of tools used in simulations'))
    op.add_column('user_descriptor', sa.Column('tools_used_count', sa.Integer(), nullable=True, comment='number of tools used in simulations'))
    op.add_column('user_descriptor', sa.Column('active_days', sa.Integer(), nullable=True, comment='count of days performing any activity'))
    op.add_column('user_descriptor', sa.Column('average_freqency', sa.Numeric(), nullable=True, comment='F = lifetime in days / Days spent on nanoHUB'))
    op.add_column('user_descriptor', sa.Column('username', sa.String(length=150), nullable=True))
    op.add_column('user_descriptor', sa.Column('name', sa.String(length=255), nullable=True))
    op.add_column('user_descriptor', sa.Column('email', sa.String(length=150), nullable=True))
    op.add_column('user_descriptor', sa.Column('registration_date', sa.DateTime(), nullable=True))
    op.add_column('user_descriptor', sa.Column('last_visit_date', sa.DateTime(), nullable=True))
    op.add_column('user_descriptor', sa.Column('lifetime_days', sa.Integer(), nullable=True, comment='last day - registration day'))
    op.create_index(op.f('ix_user_descriptor__last_updated'), 'user_descriptor', ['_last_updated'], unique=False)
    op.create_index(op.f('ix_user_descriptor_average_freqency'), 'user_descriptor', ['average_freqency'], unique=False)
    op.create_index(op.f('ix_user_descriptor_first_sim_date'), 'user_descriptor', ['first_sim_date'], unique=False)
    op.create_index(op.f('ix_user_descriptor_last_sim_date'), 'user_descriptor', ['last_sim_date'], unique=False)
    op.create_index(op.f('ix_user_descriptor_last_visit_date'), 'user_descriptor', ['last_visit_date'], unique=False)
    op.create_index(op.f('ix_user_descriptor_registration_date'), 'user_descriptor', ['registration_date'], unique=False)
    op.create_unique_constraint(None, 'user_descriptor', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_descriptor', type_='unique')
    op.drop_index(op.f('ix_user_descriptor_registration_date'), table_name='user_descriptor')
    op.drop_index(op.f('ix_user_descriptor_last_visit_date'), table_name='user_descriptor')
    op.drop_index(op.f('ix_user_descriptor_last_sim_date'), table_name='user_descriptor')
    op.drop_index(op.f('ix_user_descriptor_first_sim_date'), table_name='user_descriptor')
    op.drop_index(op.f('ix_user_descriptor_average_freqency'), table_name='user_descriptor')
    op.drop_index(op.f('ix_user_descriptor__last_updated'), table_name='user_descriptor')
    op.drop_column('user_descriptor', 'lifetime_days')
    op.drop_column('user_descriptor', 'last_visit_date')
    op.drop_column('user_descriptor', 'registration_date')
    op.drop_column('user_descriptor', 'email')
    op.drop_column('user_descriptor', 'name')
    op.drop_column('user_descriptor', 'username')
    op.drop_column('user_descriptor', 'average_freqency')
    op.drop_column('user_descriptor', 'active_days')
    op.drop_column('user_descriptor', 'tools_used_count')
    op.drop_column('user_descriptor', 'tools_used_names')
    op.drop_column('user_descriptor', 'sims_activity_days')
    op.drop_column('user_descriptor', 'sims_count')
    op.drop_column('user_descriptor', 'sims_lifetime')
    op.drop_column('user_descriptor', 'last_sim_date')
    op.drop_column('user_descriptor', 'first_sim_date')
    op.drop_column('user_descriptor', '_created')
    op.drop_column('user_descriptor', '_last_updated')
    op.drop_constraint(None, 'temp_user_descriptor', type_='unique')
    op.drop_index(op.f('ix_temp_user_descriptor_last_sim_date'), table_name='temp_user_descriptor')
    op.drop_index(op.f('ix_temp_user_descriptor_first_sim_date'), table_name='temp_user_descriptor')
    op.drop_index(op.f('ix_temp_user_descriptor_average_freqency'), table_name='temp_user_descriptor')
    op.drop_index(op.f('ix_temp_user_descriptor__last_updated'), table_name='temp_user_descriptor')
    op.drop_column('temp_user_descriptor', 'user')
    op.drop_column('temp_user_descriptor', 'average_freqency')
    op.drop_column('temp_user_descriptor', 'active_days')
    op.drop_column('temp_user_descriptor', 'tools_used_count')
    op.drop_column('temp_user_descriptor', 'tools_used_names')
    op.drop_column('temp_user_descriptor', 'sims_activity_days')
    op.drop_column('temp_user_descriptor', 'sims_count')
    op.drop_column('temp_user_descriptor', 'sims_lifetime')
    op.drop_column('temp_user_descriptor', 'last_sim_date')
    op.drop_column('temp_user_descriptor', 'first_sim_date')
    op.drop_column('temp_user_descriptor', '_created')
    op.drop_column('temp_user_descriptor', '_last_updated')
    op.drop_index(op.f('ix_record_update_history_last_processed_toolstart_id'), table_name='record_update_history')
    op.drop_column('record_update_history', 'last_processed_toolstart_id_updated')
    op.drop_column('record_update_history', 'last_processed_toolstart_id')
    # ### end Alembic commands ###
