"""Add auto-update timestamp

Revision ID: 715b24864fb1
Revises: 165b225d3c4c
Create Date: 2021-08-03 13:22:38.820394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '715b24864fb1'
down_revision = '165b225d3c4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
