"""set default datetime 3

Revision ID: 71c43bc0817e
Revises: b16a6ffc01e6
Create Date: 2021-08-03 21:23:20.910771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71c43bc0817e'
down_revision = 'b16a6ffc01e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
