"""move _created out of temp table

Revision ID: 817d26cb9ffa
Revises: 8cc1a664f1c4
Create Date: 2021-08-05 15:33:05.608744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '817d26cb9ffa'
down_revision = '8cc1a664f1c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temp_user_descriptor',
    sa.Column('_last_updated', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('first_sim_date', sa.DateTime(), nullable=True),
    sa.Column('last_sim_date', sa.DateTime(), nullable=True),
    sa.Column('sims_lifetime', sa.Integer(), nullable=True, comment='days from first to last simulation'),
    sa.Column('sims_count', sa.Integer(), nullable=True, comment='number of simulations'),
    sa.Column('tools_used_names', sa.Text(), nullable=True, comment='names of tools used in simulations'),
    sa.Column('tools_used_count', sa.Integer(), nullable=True, comment='number of tools used in simulations'),
    sa.Column('active_days', sa.Integer(), nullable=True, comment='count of days performing any activity'),
    sa.Column('average_freqency', sa.Numeric(), nullable=True, comment='F = lifetime in days / Days spent on nanoHUB'),
    sa.Column('temp_id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('temp_id'),
    sa.UniqueConstraint('user'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_temp_user_descriptor__last_updated'), 'temp_user_descriptor', ['_last_updated'], unique=False)
    op.create_index(op.f('ix_temp_user_descriptor_average_freqency'), 'temp_user_descriptor', ['average_freqency'], unique=False)
    op.create_index(op.f('ix_temp_user_descriptor_first_sim_date'), 'temp_user_descriptor', ['first_sim_date'], unique=False)
    op.create_index(op.f('ix_temp_user_descriptor_last_sim_date'), 'temp_user_descriptor', ['last_sim_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_temp_user_descriptor_last_sim_date'), table_name='temp_user_descriptor')
    op.drop_index(op.f('ix_temp_user_descriptor_first_sim_date'), table_name='temp_user_descriptor')
    op.drop_index(op.f('ix_temp_user_descriptor_average_freqency'), table_name='temp_user_descriptor')
    op.drop_index(op.f('ix_temp_user_descriptor__last_updated'), table_name='temp_user_descriptor')
    op.drop_table('temp_user_descriptor')
    # ### end Alembic commands ###
