"""individual update dates

Revision ID: 88add991bd1c
Revises: 4a8e77f0df08
Create Date: 2021-08-03 20:16:45.479651

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '88add991bd1c'
down_revision = '4a8e77f0df08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_descriptors', sa.Column('simulation_lifetime_days', sa.Integer(), nullable=True))
    op.add_column('user_descriptors', sa.Column('simulation_lifetime_days_last_updated', sa.DateTime(), nullable=False))
    op.add_column('user_descriptors', sa.Column('simulations_run_count', sa.Integer(), nullable=True))
    op.add_column('user_descriptors', sa.Column('simulations_run_count_last_updated', sa.DateTime(), nullable=False))
    op.add_column('user_descriptors', sa.Column('tools_used_names', sa.Text(), nullable=True))
    op.add_column('user_descriptors', sa.Column('tools_used_names_last_updated', sa.DateTime(), nullable=False))
    op.add_column('user_descriptors', sa.Column('tools_used_count', sa.Integer(), nullable=True))
    op.add_column('user_descriptors', sa.Column('tools_used_count_last_updated', sa.DateTime(), nullable=False))
    op.add_column('user_descriptors', sa.Column('days_spent_on_nanohub', sa.Integer(), nullable=True, comment='total number of days spent on nanoHUB'))
    op.add_column('user_descriptors', sa.Column('user_lifetime_days', sa.Integer(), nullable=True, comment='last day - registration day'))
    op.drop_index('ix_user_descriptors_name_tools_used_last_updated', table_name='user_descriptors')
    op.drop_index('ix_user_descriptors_num_tools_last_updated', table_name='user_descriptors')
    op.drop_index('ix_user_descriptors_simulations_last_updated', table_name='user_descriptors')
    op.create_index(op.f('ix_user_descriptors_simulation_lifetime_days_last_updated'), 'user_descriptors', ['simulation_lifetime_days_last_updated'], unique=False)
    op.create_index(op.f('ix_user_descriptors_simulations_run_count_last_updated'), 'user_descriptors', ['simulations_run_count_last_updated'], unique=False)
    op.create_index(op.f('ix_user_descriptors_tools_used_count_last_updated'), 'user_descriptors', ['tools_used_count_last_updated'], unique=False)
    op.create_index(op.f('ix_user_descriptors_tools_used_names_last_updated'), 'user_descriptors', ['tools_used_names_last_updated'], unique=False)
    op.drop_column('user_descriptors', 'name_tools_used')
    op.drop_column('user_descriptors', 'simulation_lifetime')
    op.drop_column('user_descriptors', 'user_lifetime')
    op.drop_column('user_descriptors', 'num_days_spent')
    op.drop_column('user_descriptors', 'num_simulations_run')
    op.drop_column('user_descriptors', 'simulations_last_updated')
    op.drop_column('user_descriptors', 'num_tools_used')
    op.drop_column('user_descriptors', 'name_tools_used_last_updated')
    op.drop_column('user_descriptors', 'num_tools_last_updated')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_descriptors', sa.Column('num_tools_last_updated', mysql.DATETIME(), nullable=False))
    op.add_column('user_descriptors', sa.Column('name_tools_used_last_updated', mysql.DATETIME(), nullable=False))
    op.add_column('user_descriptors', sa.Column('num_tools_used', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('user_descriptors', sa.Column('simulations_last_updated', mysql.DATETIME(), nullable=False))
    op.add_column('user_descriptors', sa.Column('num_simulations_run', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('user_descriptors', sa.Column('num_days_spent', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='total number of days spent on nanoHUB'))
    op.add_column('user_descriptors', sa.Column('user_lifetime', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='last day - registration day'))
    op.add_column('user_descriptors', sa.Column('simulation_lifetime', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('user_descriptors', sa.Column('name_tools_used', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True))
    op.drop_index(op.f('ix_user_descriptors_tools_used_names_last_updated'), table_name='user_descriptors')
    op.drop_index(op.f('ix_user_descriptors_tools_used_count_last_updated'), table_name='user_descriptors')
    op.drop_index(op.f('ix_user_descriptors_simulations_run_count_last_updated'), table_name='user_descriptors')
    op.drop_index(op.f('ix_user_descriptors_simulation_lifetime_days_last_updated'), table_name='user_descriptors')
    op.create_index('ix_user_descriptors_simulations_last_updated', 'user_descriptors', ['simulations_last_updated'], unique=False)
    op.create_index('ix_user_descriptors_num_tools_last_updated', 'user_descriptors', ['num_tools_last_updated'], unique=False)
    op.create_index('ix_user_descriptors_name_tools_used_last_updated', 'user_descriptors', ['name_tools_used_last_updated'], unique=False)
    op.drop_column('user_descriptors', 'user_lifetime_days')
    op.drop_column('user_descriptors', 'days_spent_on_nanohub')
    op.drop_column('user_descriptors', 'tools_used_count_last_updated')
    op.drop_column('user_descriptors', 'tools_used_count')
    op.drop_column('user_descriptors', 'tools_used_names_last_updated')
    op.drop_column('user_descriptors', 'tools_used_names')
    op.drop_column('user_descriptors', 'simulations_run_count_last_updated')
    op.drop_column('user_descriptors', 'simulations_run_count')
    op.drop_column('user_descriptors', 'simulation_lifetime_days_last_updated')
    op.drop_column('user_descriptors', 'simulation_lifetime_days')
    # ### end Alembic commands ###
