"""add class LastUpdateRecord

Revision ID: 89b7ce13bc5d
Revises: 8cce1471fa6d
Create Date: 2021-08-04 11:41:32.584819

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '89b7ce13bc5d'
down_revision = '8cce1471fa6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('last_update_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_processed_toolstart_id', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('last_processed_toolstart_id_updated', sa.DateTime(), nullable=True),
    sa.Column('timestamp_last_updated', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_last_update_record_last_processed_toolstart_id'), 'last_update_record', ['last_processed_toolstart_id'], unique=False)
    op.create_index(op.f('ix_last_update_record_timestamp_last_updated'), 'last_update_record', ['timestamp_last_updated'], unique=False)
    op.drop_index('ix_user_descriptors_last_toolstart_id_processed', table_name='user_descriptors')
    op.drop_column('user_descriptors', 'last_toolstart_id_processed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_descriptors', sa.Column('last_toolstart_id_processed', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False))
    op.create_index('ix_user_descriptors_last_toolstart_id_processed', 'user_descriptors', ['last_toolstart_id_processed'], unique=False)
    op.drop_index(op.f('ix_last_update_record_timestamp_last_updated'), table_name='last_update_record')
    op.drop_index(op.f('ix_last_update_record_last_processed_toolstart_id'), table_name='last_update_record')
    op.drop_table('last_update_record')
    # ### end Alembic commands ###
