"""remove sims_activity_days

Revision ID: 8cc1a664f1c4
Revises: 6757b3cea427
Create Date: 2021-08-05 15:31:50.159838

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8cc1a664f1c4'
down_revision = '6757b3cea427'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_temp_user_descriptor__last_updated', table_name='temp_user_descriptor')
    op.drop_index('ix_temp_user_descriptor_average_freqency', table_name='temp_user_descriptor')
    op.drop_index('ix_temp_user_descriptor_first_sim_date', table_name='temp_user_descriptor')
    op.drop_index('ix_temp_user_descriptor_last_sim_date', table_name='temp_user_descriptor')
    op.drop_table('temp_user_descriptor')
    op.drop_column('user_descriptor', 'sims_activity_days')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_descriptor', sa.Column('sims_activity_days', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='count of days spent performing simulations'))
    op.create_table('temp_user_descriptor',
    sa.Column('index', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('user', mysql.TEXT(), nullable=True),
    sa.Column('sims_lifetime', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True, comment='days from first to last simulation'),
    sa.Column('tools_used_count', mysql.TEXT(), nullable=True, comment='number of tools used in simulations'),
    sa.Column('sims_count', mysql.DOUBLE(asdecimal=True), nullable=True, comment='number of simulations'),
    sa.Column('first_sim_date', mysql.DATETIME(), nullable=True),
    sa.Column('last_sim_date', mysql.DATETIME(), nullable=True),
    sa.Column('_last_updated', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('_created', mysql.DATETIME(), nullable=True),
    sa.Column('tools_used_names', mysql.TEXT(), nullable=True, comment='names of tools used in simulations'),
    sa.Column('active_days', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='count of days performing any activity'),
    sa.Column('average_freqency', mysql.DECIMAL(precision=10, scale=0), nullable=True, comment='F = lifetime in days / Days spent on nanoHUB'),
    sa.Column('temp_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_temp_user_descriptor_last_sim_date', 'temp_user_descriptor', ['last_sim_date'], unique=False)
    op.create_index('ix_temp_user_descriptor_first_sim_date', 'temp_user_descriptor', ['first_sim_date'], unique=False)
    op.create_index('ix_temp_user_descriptor_average_freqency', 'temp_user_descriptor', ['average_freqency'], unique=False)
    op.create_index('ix_temp_user_descriptor__last_updated', 'temp_user_descriptor', ['_last_updated'], unique=False)
    # ### end Alembic commands ###
