"""set default datetime

Revision ID: 8f1632f17388
Revises: 88add991bd1c
Create Date: 2021-08-03 20:25:39.601453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f1632f17388'
down_revision = '88add991bd1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
