"""add temp table

Revision ID: 8ffc49054640
Revises: bf719527544b
Create Date: 2021-08-05 16:17:09.948811

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8ffc49054640'
down_revision = 'bf719527544b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_rfm_data.temp_user_descriptor_index', table_name='rfm_data.temp_user_descriptor')
    op.drop_table('rfm_data.temp_user_descriptor')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rfm_data.temp_user_descriptor',
    sa.Column('index', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('user', mysql.TEXT(), nullable=True),
    sa.Column('sims_lifetime', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('tools_used_count', mysql.TEXT(), nullable=True),
    sa.Column('sims_count', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('first_sim_date', mysql.DATETIME(), nullable=True),
    sa.Column('last_sim_date', mysql.DATETIME(), nullable=True),
    sa.Column('sim_activity_days', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_rfm_data.temp_user_descriptor_index', 'rfm_data.temp_user_descriptor', ['index'], unique=False)
    # ### end Alembic commands ###
