"""set default datetime 4

Revision ID: 94961cbb94c5
Revises: 71c43bc0817e
Create Date: 2021-08-03 21:24:40.093106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94961cbb94c5'
down_revision = '71c43bc0817e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
