"""add temp table

Revision ID: 9ef59aa99a7d
Revises: 8ffc49054640
Create Date: 2021-08-05 16:28:18.217511

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9ef59aa99a7d'
down_revision = '8ffc49054640'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_descriptor__last_updated', table_name='user_descriptor')
    op.drop_index('ix_user_descriptor_average_freqency', table_name='user_descriptor')
    op.drop_index('ix_user_descriptor_first_sim_date', table_name='user_descriptor')
    op.drop_index('ix_user_descriptor_last_sim_date', table_name='user_descriptor')
    op.drop_index('ix_user_descriptor_last_visit_date', table_name='user_descriptor')
    op.drop_index('ix_user_descriptor_registration_date', table_name='user_descriptor')
    op.drop_index('username', table_name='user_descriptor')
    op.drop_column('user_descriptor', 'username')
    op.drop_column('user_descriptor', 'email')
    op.drop_column('user_descriptor', 'last_sim_date')
    op.drop_column('user_descriptor', 'first_sim_date')
    op.drop_column('user_descriptor', 'active_days')
    op.drop_column('user_descriptor', 'sims_count')
    op.drop_column('user_descriptor', 'tools_used_count')
    op.drop_column('user_descriptor', 'sims_lifetime')
    op.drop_column('user_descriptor', 'lifetime_days')
    op.drop_column('user_descriptor', 'registration_date')
    op.drop_column('user_descriptor', 'last_visit_date')
    op.drop_column('user_descriptor', 'name')
    op.drop_column('user_descriptor', 'sims_activity_days')
    op.drop_column('user_descriptor', '_created')
    op.drop_column('user_descriptor', '_last_updated')
    op.drop_column('user_descriptor', 'average_freqency')
    op.drop_column('user_descriptor', 'tools_used_names')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_descriptor', sa.Column('tools_used_names', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True, comment='names of tools used in simulations'))
    op.add_column('user_descriptor', sa.Column('average_freqency', mysql.DECIMAL(precision=10, scale=0), nullable=True, comment='F = lifetime in days / Days spent on nanoHUB'))
    op.add_column('user_descriptor', sa.Column('_last_updated', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False))
    op.add_column('user_descriptor', sa.Column('_created', mysql.DATETIME(), nullable=True))
    op.add_column('user_descriptor', sa.Column('sims_activity_days', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='count of days spent performing simulations'))
    op.add_column('user_descriptor', sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
    op.add_column('user_descriptor', sa.Column('last_visit_date', mysql.DATETIME(), nullable=True))
    op.add_column('user_descriptor', sa.Column('registration_date', mysql.DATETIME(), nullable=True))
    op.add_column('user_descriptor', sa.Column('lifetime_days', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='last day - registration day'))
    op.add_column('user_descriptor', sa.Column('sims_lifetime', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='days from first to last simulation'))
    op.add_column('user_descriptor', sa.Column('tools_used_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='number of tools used in simulations'))
    op.add_column('user_descriptor', sa.Column('sims_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='number of simulations'))
    op.add_column('user_descriptor', sa.Column('active_days', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='count of days performing any activity'))
    op.add_column('user_descriptor', sa.Column('first_sim_date', mysql.DATETIME(), nullable=True))
    op.add_column('user_descriptor', sa.Column('last_sim_date', mysql.DATETIME(), nullable=True))
    op.add_column('user_descriptor', sa.Column('email', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=150), nullable=True))
    op.add_column('user_descriptor', sa.Column('username', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=150), nullable=True))
    op.create_index('username', 'user_descriptor', ['username'], unique=False)
    op.create_index('ix_user_descriptor_registration_date', 'user_descriptor', ['registration_date'], unique=False)
    op.create_index('ix_user_descriptor_last_visit_date', 'user_descriptor', ['last_visit_date'], unique=False)
    op.create_index('ix_user_descriptor_last_sim_date', 'user_descriptor', ['last_sim_date'], unique=False)
    op.create_index('ix_user_descriptor_first_sim_date', 'user_descriptor', ['first_sim_date'], unique=False)
    op.create_index('ix_user_descriptor_average_freqency', 'user_descriptor', ['average_freqency'], unique=False)
    op.create_index('ix_user_descriptor__last_updated', 'user_descriptor', ['_last_updated'], unique=False)
    # ### end Alembic commands ###
