"""set default datetime 2

Revision ID: b16a6ffc01e6
Revises: 8f1632f17388
Create Date: 2021-08-03 20:43:13.986355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b16a6ffc01e6'
down_revision = '8f1632f17388'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
