"""remove temp table

Revision ID: bf719527544b
Revises: e89454fd1a29
Create Date: 2021-08-05 16:09:51.859547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf719527544b'
down_revision = 'e89454fd1a29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
