"""add sims_activity_days

Revision ID: e89454fd1a29
Revises: 817d26cb9ffa
Create Date: 2021-08-05 15:39:31.173680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e89454fd1a29'
down_revision = '817d26cb9ffa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('temp_user_descriptor', sa.Column('sims_activity_days', sa.Integer(), nullable=True, comment='count of days spent performing simulations'))
    op.add_column('user_descriptor', sa.Column('sims_activity_days', sa.Integer(), nullable=True, comment='count of days spent performing simulations'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_descriptor', 'sims_activity_days')
    op.drop_column('temp_user_descriptor', 'sims_activity_days')
    # ### end Alembic commands ###
