"""Add auto-update timestamp

Revision ID: ea6a1797aff9
Revises: 25aa6780c58c
Create Date: 2021-08-03 13:23:53.386987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea6a1797aff9'
down_revision = '25aa6780c58c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_descriptors', sa.Column('last_updated', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_user_descriptors_last_updated'), 'user_descriptors', ['last_updated'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_descriptors_last_updated'), table_name='user_descriptors')
    op.drop_column('user_descriptors', 'last_updated')
    # ### end Alembic commands ###
