"""auto-create and auto-update timestamp

Revision ID: fd274a13bca4
Revises: 413305d45a5b
Create Date: 2021-08-03 13:34:36.228812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd274a13bca4'
down_revision = '413305d45a5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_descriptors', sa.Column('timestamp_last_updated', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False))
    op.add_column('user_descriptors', sa.Column('timestamp_created', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_user_descriptors_timestamp_last_updated'), 'user_descriptors', ['timestamp_last_updated'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_descriptors_timestamp_last_updated'), table_name='user_descriptors')
    op.drop_column('user_descriptors', 'timestamp_created')
    op.drop_column('user_descriptors', 'timestamp_last_updated')
    # ### end Alembic commands ###
